repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    - id: trailing-whitespace
    - id: end-of-file-fixer
    - id: check-yaml
    - id: check-json
    - id: mixed-line-ending
      args: ['--fix=no']
    - id: check-added-large-files
      args: ['--maxkb=500']
    - id: name-tests-test
      args: ['--pytest-test-first']
    - id: no-commit-to-branch
      args: [--branch, main, --branch, master]
    - id: requirements-txt-fixer
-   repo: https://github.com/psf/black-pre-commit-mirror
    rev: 23.11.0
    hooks:
    - id: black
      language_version: python3.10
      stages: [commit]
-   repo: https://github.com/pycqa/flake8
    rev: 6.1.0
    hooks:
    - id: flake8
      additional_dependencies: [flake8-docstrings]
      stages: [commit]
-   repo: local
    hooks:
    - id: pytest
      name: pytest
      language: system
      entry: pytest -v
      always_run: true
      pass_filenames: false
      stages: [commit]
# -   repo: local
#     hooks:
#       - id: requirements
#         name: requirements
#         entry: bash -c 'venv/bin/pip3 freeze > requirements.txt; git add requirements.txt'
#         language: system
#         pass_filenames: false
#         stages: [commit]
