
steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Google Auth
      id: auth
      uses: 'google-github-actions/auth@v2'
      with:
        credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}' # Replace with the name of your GitHub Actions secret

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v0

    - name: Register gcloud as a Docker credential helper
      run: gcloud auth configure-docker us-central1-docker.pkg.dev

    - name: build
      run: gcloud builds submit --region=us-central1 --tag us-central1-docker.pkg.dev/apinomes/api-projetos-images/youtube-commets-analysis
