on:
  workflow_call

jobs:
  _deployment_dev:
    runs-on: ubuntu-latest
    environment:
      name: ${{ github.ref_name }}
    steps:
        - name: Checkout
          uses: actions/checkout@v3

        - name: Google Auth
          id: auth
          uses: 'google-github-actions/auth@v2'
          with:
            credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'

        - name: Set up Google Cloud SDK
          uses: google-github-actions/setup-gcloud@v2.0.1

        - name: Register gcloud as a Docker credential helper
          run: |
            gcloud auth configure-docker us-central1-docker.pkg.dev
            echo "Listando gcloud info"
            gcloud info

        - name: build
          run: gcloud builds submit --verbosity=debug --region=us-central1 --tag us-central1-docker.pkg.dev/apinomes/api-projetos-images/youtube-commets-analysis
