on:
  push:
    branches: [dev, main]

jobs:
  dev:
    name: deploy cloudrun to dev environment
    if: ${{ github.ref == 'refs/heads/develop' || github.base_ref == 'develop' }}
    uses: ./.github/workflows/_deployment_dev.yaml
    permissions:
      id-token: write
      contents: read
    with:
      environment: dev
      ref: ${{ github.sha }}
    secrets: inherit
  # prod:
  #   if: ${{ github.ref == 'refs/heads/main' || github.base_ref == 'main' }}
  #   uses: ./.github/workflows/_deployment_prd.yaml
  #   permissions:
  #     id-token: write
  #     contents: read
  #   with:
  #     environment: prod
  #     ref: ${{ github.sha }}
  #   secrets: inherit
