name: Deploy to Cloud Run

on:
  push:
    branches:
      - 'dev'
      - 'main'

jobs:
  dev:
    name: Deploy cloudrun to dev environment
    if: ${{ github.ref == 'refs/heads/dev' }}
    environment:
      name: ${{ github.ref_name }}
    uses: ./.github/workflows/deploy.yaml
    permissions:
      id-token: write
      contents: read
    secrets: inherit
  # prod:
  #   if: ${{ github.ref == 'refs/heads/main' || github.base_ref == 'main' }}
  #   uses: ./.github/workflows/_deployment_prd.yaml
  #   permissions:
  #     id-token: write
  #     contents: read
  #   with:
  #     environment: prod
  #     ref: ${{ github.sha }}
  #   secrets: inherit
